#source "/usr/share/powerline/bindings/tmux/powerline.conf"
set -g default-terminal "st-256color"
set -as terminal-overrides ",gnome*:RGB"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'

setw -g mode-keys vi

set -g mouse on

bind-key : command-prompt
bind-key r refresh-client
bind-key L clear-history

# use <prefix> s for horizontal split
bind b split-window -v
# use <prefix> v for vertical split
bind v split-window -h

bind < resize-pane -L 10
bind > resize-pane -R 10
bind - resize-pane -D 10
bind + resize-pane -U 10

bind-key space next-window
bind-key bspace previous-window
bind-key enter next-layout

bind-key v split-window -h
bind-key s split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


