
setw -g mode-keys vi

set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'




bind-key s split-window -h
bind-key v split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R



bind < resize-pane -L 10
bind > resize-pane -R 10
bind - resize-pane -D 10
bind + resize-pane -U 10




run '~/.tmux/plugins/tpm/tpm'


#set -g default-terminal "xterm-256color"
#set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
#set -as terminal-overrides ",gnome*:RGB"
#bind-key : command-prompt
#bind-key r refresh-client
#bind-key L clear-history
#
## use <prefix> s for horizontal split
#bind b split-window -v
## use <prefix> v for vertical split
#bind v split-window -h
#
#
#bind-key space next-window
#bind-key bspace previous-window
#bind-key enter next-layout
#
#
#set-option -g status on
#set-option -g status-interval 2
#set-option -g status-justify "centre"
#set-option -g status-left-length 60
#set-option -g status-right-length 90
#set-option -g status-left "#(~/install/tmux-powerline/powerline.sh left)"
#set-option -g status-right "#(~/install/tmux-powerline/powerline.sh right)"

